### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by seanmars** [jblakeman/apt-select#61]
```
# apt-select --help
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/apt_select/apt_system.py", line 33, in AptSystem
    dist, codename = get_release.__func__()
  File "/usr/local/lib/python3.5/dist-packages/apt_select/apt_system.py", line 21, in get_release
    for s in check_output(["lsb_release", "-ics"]).split()]
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'lsb_release'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/apt-select", line 11, in <module>
    load_entry_point('apt-select==1.0.3', 'console_scripts', 'apt-select')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/apt_select/__main__.py", line 8, in <module>
    from apt_select.mirrors import Mirrors
  File "/usr/local/lib/python3.5/dist-packages/apt_select/mirrors.py", line 11, in <module>
    from apt_select.apt_system import AptSystem
  File "/usr/local/lib/python3.5/dist-packages/apt_select/apt_system.py", line 14, in <module>
    class AptSystem(object):
  File "/usr/local/lib/python3.5/dist-packages/apt_select/apt_system.py", line 35, in AptSystem
    raise ValueError("%s\n%s" % _not_ubuntu)
TypeError: not enough arguments for format string
```

**Comment by jblakeman** [comment]
Thanks, this is admittedly a careless string formatting bug in the error message that should be fixed.

I'm guessing this is either not being run on Ubuntu or your `PATH` been modified to exclude `/usr/bin` since AFAIK all Ubuntu systems should have the `lsb_release` installed in `PATH`.

**Comment by seanmars** [comment]
> I'm guessing this is either not being run on Ubuntu or your PATH been modified to exclude /usr/bin since AFAIK all Ubuntu systems should have the lsb_release installed in PATH.

This may be the key point that I'm using the apt-select on docker.

**Comment by jblakeman** [comment]
> This may be the key point that I'm using the apt-select on docker(official Docker image for Ubuntu).

That helps me better understand the issue.

`lsb_release` is missing in Ubuntu's [rootfs](https://partner-images.canonical.com/core/) (which are the source of the official docker images).

The apparent solution is to fall back to reading the contents of `/etc/lsb-release` since that file is included in the root filesystem.

**Comment by luckydonald** [comment]
Is there some way to run it outside of windows, to just get a list of mirrors?
